apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-svc
spec:
  selector:
    matchLabels:
      app: cart-svc
  template:
    metadata:
      labels:
        app: cart-svc
    spec:
      containers:
      - name: cart-svc
        image: bogdan243/cart-svc
        imagePullPolicy: Never
        envFrom:
          - configMapRef:
              name: cart-svc-config
        ports:
        - containerPort: 80
          name: web
---
apiVersion: v1
kind: Service
metadata:
  name: cart-clusterip
spec:
  selector:
    app: cart-svc
  ports:
  - port: 80
    targetPort: 80
    name: web
