apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-svc
spec:
  selector:
    matchLabels:
      app: gateway-svc
  template:
    metadata:
      labels:
        app: gateway-svc
    spec:
      containers:
      - name: gateway-svc
        image: bogdan243/gateway-svc
        imagePullPolicy: Never
        envFrom:
          - configMapRef:
              name: gateway-svc-config
        ports:
        - containerPort: 80
          name: web
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-np
spec:
  type: NodePort
  selector:
    app: gateway-svc
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30004
    name: web
