apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-svc
spec:
  selector:
    matchLabels:
      app: order-svc
  template:
    metadata:
      labels:
        app: order-svc
    spec:
      containers:
      - name: order-svc
        image: bogdan243/order-svc
        imagePullPolicy: Never
        envFrom:
          - configMapRef:
              name: order-svc-config
        ports:
        - containerPort: 80
          name: web
---
apiVersion: v1
kind: Service
metadata:
  name: order-clusterip
spec:
  selector:
    app: order-svc
  ports:
  - port: 80
    targetPort: 80
    name: web
