apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-svc
spec:
  selector:
    matchLabels:
      app: product-svc
  template:
    metadata:
      labels:
        app: product-svc
    spec:
      containers:
      - name: product-svc
        image: bogdan243/product-svc
        imagePullPolicy: Never
        envFrom:
          - configMapRef:
              name: product-svc-config
        ports:
        - containerPort: 80
          name: web
---
apiVersion: v1
kind: Service
metadata:
  name: product-clusterip
spec:
  selector:
    app: product-svc
  ports:
  - port: 80
    targetPort: 80
    name: web
