apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-svc
spec:
  selector:
    matchLabels:
      app: user-svc
  template:
    metadata:
      labels:
        app: user-svc
    spec:
      containers:
      - name: user-svc
        image: bogdan243/user-svc
        imagePullPolicy: Never
        envFrom:
          - configMapRef:
              name: user-svc-config
        ports:
        - containerPort: 80
          name: web
---
apiVersion: v1
kind: Service
metadata:
  name: user-np
spec:
  type: NodePort
  selector:
    app: user-svc
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30006
    name: web
