# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore Emag
    - name: Build Products
      run: dotnet build Emag
    - name: Build Order
      run: dotnet build OrderService
    - name: Build User
      run: dotnet build UserService
    - name: Build Gateway
      run: dotnet build GatewayService
    - name: Build Cart
      run: |
        cd Carts
        dotnet build CartsService
      
